on: 
  push:
    branches:
     - main
name: 🚀 Deploy PRIM to dev domain
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.prim.my
        username: admin@prim.my
        password: ${{ secrets.ftp_password }}
        local-dir: /
        server-dir:  /dev.prim.my/lsapp/